language: dart

before_install:
  - npm install -g superstatic
  - pub global activate linkcheck
  - pub global activate webdev
  - chmod +x ./tool/check_links.sh
  - chmod +x ./tool/deploy.sh

script:
  - make build
  - ./tool/check_links.sh

deploy:
  - provider: script
    script: ./tool/deploy.sh
    skip_cleanup: true
