name: filiphnet2017
description: Filip Hracek's homepage + associated tooling.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  args: ^2.4.2
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  html: ^0.15.4
  intl: ^0.19.0
  markdown: ^7.1.1
  path: ^1.8.3
  toml: ^0.14.0
  yaml: ^3.1.2
