name: filiphnet2017
description: Filip Hracek's homepage + associated tooling.
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  args: ^1.5.1
  build_runner: ^1.6.2
  build_web_compilers: ^2.1.0
  html: ^0.14.0+2
  markdown: ^2.0.3
